//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRACKED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_PRODUCTO
    {
        public int idPedidoProducto { get; set; }
        public int idPedido { get; set; }
        public int Idproducto { get; set; }
        public int IdEstado { get; set; }
        public int IdCliente { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<double> valorProducto { get; set; }
        public Nullable<int> porcion { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
