//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRACKED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_PRODUCTOS
    {
        public Nullable<int> idPedidoProducto { get; set; }
        public Nullable<int> idPedido { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<decimal> valorProducto { get; set; }
        public Nullable<int> porcion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacionTabla { get; set; }
        public int idRegistroProducto { get; set; }
    }
}
