//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRACKED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_PRODUCTO()
        {
            this.PRODUCTOes = new HashSet<PRODUCTO>();
        }
    
        public int idTipoProducto { get; set; }
        public int idEstado { get; set; }
        public string nombre { get; set; }
        public Nullable<int> idSabor { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO> PRODUCTOes { get; set; }
        public virtual SABOR SABOR { get; set; }
    }
}
